spring:
  datasource:
    url: jdbc:hsqldb:mem:myDb;DB_CLOSE_DELAY=-1
    username:
    data-password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update